import { Injectable, StreamableFile } from '@nestjs/common';
import { DbService } from '../db/db.service'
import { ProfileDTO } from './dto/profile-d-t-o';
import { createReadStream } from 'fs';
import {writeFile} from 'fs';
import { promisify } from 'util';

@Injectable()
export class ContentService {
  constructor(private dbService: DbService) {}

  async updateVideoModerationStatus(data): Promise<any> {
    let dataToUpdate = {
      under_moderation: false,
      allowed: data.allowed
    }

    if (data.allowed) {
      dataToUpdate['preview_url'] = data?.previewImage ?? ''
    }

    return this.dbService.video.update({
      data: dataToUpdate,
      where: {
        id: data.videoId
      }
    })
  }


  async deleteVideo(videoId: string): Promise<any> {
    return this.dbService.video.update({
      where: {
        id: parseInt(videoId)
      },
      data: {
        under_moderation: false,
        allowed: false,
        deleted: true
      }
    })
  }

  async uploadContent(userId: number, data: ProfileDTO, videoId: number): Promise<any> {
    return this.dbService.user.update({
      where: {
        id: userId
      },
      data: {
        image: data.image,
        name: data.name,
        lastname: data.lastname,
        phone_number: data.phone_number.toString(),
        email: data.email,
        city: data.city,
        social_media_link: data.social_media_link,
        age: parseInt(String(data.age)),
        videos: {
          connect: {
            id: videoId
          }
        }
      },
    })
  }

  async uploadSong(data: any): Promise<any> {
    return this.dbService.song.create({
      data: {
        ...data
      }
    })
  }

  async getSongs(): Promise<any> {
    return this.dbService.song.findMany({
      orderBy: {
        id: 'desc'
      }
    })
  }

  async getVideosToModerate(skip: string): Promise<any> {
    const videos = await this.dbService.$queryRaw`
    Select *, video.id as video_d from videos as video
    JOIN users as userc on video.user_id = userc.id
    JOIN song as ss on ss.id = video.song_id
    WHERE NOT video.allowed AND video.under_moderation IS TRUE AND NOT video.deleted
    ORDER BY video.created_at ASC
    LIMIT 10 OFFSET ${parseInt(skip)}
    `

    if (!Array.isArray(videos)) {
      return []
    }

    return videos.map(video => {
      return {
        ...video,
        id: video.video_d,
        users: {
          name: video.name,
          lastname: video.lastname,
          city: video.city,
          age: video.age,
          email: video.email,
          image: video.image,
          phone_number: video.phone_number,
          social_media_link: video.social_media_link
        },
        song: {
          author_name: video.author_name,
          title: video.title,
          image_link: video.image_link
        },
      }
    })
  }

  async getDeclinedVideos(skip: string): Promise<any> {
    const videos = await this.dbService.$queryRaw`
    Select *, video.id as video_d from videos as video
    JOIN users as userc on video.user_id = userc.id
    JOIN song as ss on ss.id = video.song_id
    WHERE NOT video.allowed AND NOT video.under_moderation AND NOT video.deleted
    ORDER BY video.created_at DESC
    LIMIT 10 OFFSET ${parseInt(skip)}
    `

    if (!Array.isArray(videos)) {
      return []
    }

    return videos.map(video => {
      return {
        ...video,
        id: video.video_d,
        users: {
          name: video.name,
          lastname: video.lastname,
          city: video.city,
          age: video.age,
          email: video.email,
          image: video.image,
          phone_number: video.phone_number,
          social_media_link: video.social_media_link
        },
        song: {
          author_name: video.author_name,
          title: video.title,
          image_link: video.image_link
        },
      }
    })
  }

  async getDeclinedVideosCount(): Promise<any> {
    const declinedVideosCount = await this.dbService.$queryRaw`
    Select COUNT(video.*) as countToShow from videos as video
    WHERE NOT video.allowed AND NOT video.under_moderation AND NOT video.deleted`

    const acceptedVideosCount = await this.dbService.$queryRaw`
    Select COUNT(video.*) as countToShow from videos as video
    WHERE video.allowed IS TRUE AND NOT video.under_moderation AND NOT video.deleted`

    const underModerationVideosCount = await this.dbService.$queryRaw`
    Select COUNT(video.*) as countToShow from videos as video
    WHERE NOT video.allowed AND video.under_moderation IS TRUE AND NOT video.deleted`

    const totalModerationVideosCount = await this.dbService.$queryRaw`
    Select COUNT(video.*) as countToShow from videos as video WHERE NOT video.deleted`

    if (!declinedVideosCount || declinedVideosCount == 'unknown') {
      return 0
    }

    // @ts-ignore
    return {
      accepted: parseInt(acceptedVideosCount[0]?.counttoshow ?? 0),
      declined: parseInt(declinedVideosCount[0]?.counttoshow ?? 0),
      underModeration: parseInt(underModerationVideosCount[0]?.counttoshow ?? 0),
      total: parseInt(totalModerationVideosCount[0]?.counttoshow ?? 0)
    }
  }

  async getApprovedVideos(skip: string): Promise<any> {
    const videos = await this.dbService.$queryRaw`
    Select *, video.id as video_d from videos as video
    JOIN users as userc on video.user_id = userc.id
    JOIN song as ss on ss.id = video.song_id
    WHERE video.allowed IS TRUE AND video.under_moderation IS FALSE
    ORDER BY video.id DESC
    LIMIT 10 OFFSET ${parseInt(skip)}
    `

    if (!Array.isArray(videos)) {
      return []
    }

    return videos.map(video => {
      return {
        ...video,
        id: video.video_d,
        users: {
          name: video.name,
          lastname: video.lastname,
          city: video.city,
          age: video.age,
          email: video.email,
          image: video.image,
          phone_number: video.phone_number,
          social_media_link: video.social_media_link
        },
        song: {
          author_name: video.author_name,
          title: video.title,
          image_link: video.image_link
        },
      }
    })
  }

  async getContent(id: number): Promise<any> {
    return {};
    // return this.dbService.video.findMany({
    //   //take: 3, // TODO: remove
    //   where: {
    //     id: {
    //       not: {
    //         lt: 6
    //       }
    //     },
    //     under_moderation: false,
    //     allowed: true
    //   },
    //   orderBy: {
    //     videoLikes: {
    //       _count: 'desc'
    //     }
    //   },
    //   include: {
    //     users: true,
    //     song: true,
    //     videoLikes: {
    //       select: {
    //         id: true,
    //         video_id: true,
    //         user: {
    //           select: {
    //             id: true,
    //           },
    //         },
    //       },
    //     }
    //   }
    // })
  }

  async findManyVideosByUsername(skip: string, query: string, userId: number, startVideoId: string): Promise<any> {
    const queryToUse = query == 'null' ? '' : query
    const videos = await this.dbService.$queryRaw`
    Select *, video.id as video_d, (SELECT count(*) from video_likes as videoLike where videoLike.video_id = video.id AND videoLike.user_id = ${userId}) as is_liked_by_me, (SELECT count(*) from video_likes as videoLike where videoLike.video_id = video.id) as video_likes from videos as video
    JOIN users as userc on video.user_id = userc.id
    JOIN song as ss on ss.id = video.song_id
    WHERE video.allowed AND (LOWER(CONCAT(userc.lastname, ' ', userc.name)) LIKE LOWER(${'%' + queryToUse + '%'}) OR LOWER(CONCAT(userc.name, ' ', userc.lastname)) LIKE LOWER(${'%' + queryToUse + '%'}) OR LOWER(userc.name) LIKE LOWER(${'%' + queryToUse + '%'}) OR LOWER(ss.title) LIKE LOWER(${'%' + queryToUse + '%'}))
    ORDER BY (SELECT count(*) from video_likes as videoLike where videoLike.video_id = video.id) DESC, video.created_at ASC
    LIMIT 10 OFFSET ${parseInt(skip)}
    `

    if (!Array.isArray(videos)) {
      return []
    }

    return videos.map(video => {
      return {
        ...video,
        id: video.video_d,
        users: {
          name: video.name,
          lastname: video.lastname,
          city: video.city,
          age: video.age,
          email: video.email,
          image: video.image
        },
        song: {
          author_name: video.author_name,
          title: video.title,
          image_link: video.image_link
        },
        video_likes: '',
        is_liked_by_me: parseInt(video.is_liked_by_me) > 0,
        videoLikes: parseInt(video.video_likes)
      }
    })
  }

  async cleanUsers(query: string): Promise<any> {
    // let data = ''
    // readXlsxFile('/Users/bohdanoskin/Documents/Other/extreme/domains/backend/src/content/ert.xlsx').then(rows => {
    //   for (const row in rows) {
    //     data += ('"' + rows[row][0] + '",\n')
    //   }
    //   this.createFile('/Users/bohdanoskin/Documents/Other/extreme/domains/backend/src/content', 'er.txt', data);
    // })
    //
    // return
    // const queryToUse = query == 'null' ? '' : query
    // if (queryToUse == '') {
    //   return {}
    // }

    return await this.dbService.$queryRaw`
        Delete from users as usr
        WHERE usr.email IN(
                           'krasilnikovapyl1990@list.ru',
                           'd5871afe1f@emailfoxi.pro',
                           'dfpuysorwb@rambler.ru',
                           'dorofeevazjt1987@list.ru',
                           'golubevahhz1972@list.ru',
                           'anfa.wakeland@inboxorigin.com',
                           '8r9oy63v@maxamba.com',
                           'gorbachyovatxd1969@list.ru',
                           'imytjgaryc@rambler.ru',
                           '2bd29791c2@emailfoxi.pro',
                           'simonkudryashov1996@list.ru',
                           '4m4gmts8@maxamba.com',
                           'denisovaeyw1997@list.ru',
                           'subbotinacur1988@list.ru',
                           'wjvlhhrztc@rambler.ru',
                           'volkovawpb1977@list.ru',
                           'jayger.herzberg@easymailer.live',
                           'eliseevamyz1985@list.ru',
                           '155eefcbe9@emailfoxi.pro',
                           '53g25sby@maxamba.com',
                           'mikheevahme1982@list.ru',
                           'qietgywmqt@rambler.ru',
                           'prokhorovaajs1997@list.ru',
                           'sobolevapez1996@list.ru',
                           'a5efb375da@emailfoxi.pro',
                           'vtn0m95u@maxamba.com',
                           'fokinakew1997@list.ru',
                           'clydene.clontz@mailmagnet.co',
                           'sokolovabic1991@list.ru',
                           'melentiisuvorov1996@list.ru',
                           'sorokinajun1976@list.ru',
                           'sjgosgacpk@rambler.ru',
                           'yitm61g9@maxamba.com',
                           'tretyakovapjo1969@list.ru',
                           '0503b889b0@emailfoxi.pro',
                           'oleg_gavrilov_1977@list.ru',
                           'nosovaplt1985@list.ru',
                           '2oivurkf@maxamba.com',
                           'khaylani.hirst@easymailer.live',
                           'rt25qejx@maxamba.com',
                           'kulikovayuu1993@list.ru',
                           'panovasgj1976@list.ru',
                           'fokinaayw1975@list.ru',
                           'sazonovaqxj1990@list.ru',
                           'zuevaexs1988@list.ru',
                           'frolovaqsm1993@list.ru',
                           'wlo8xl0w@maxamba.com',
                           'kudryavtsevaszr1966@list.ru',
                           'wksjrmofpj@rambler.ru',
                           'fokinaual1990@list.ru',
                           'rodionovapzk1985@list.ru',
                           'tkvz964l@maxamba.com',
                           'urwmhtavtb@rambler.ru',
                           'vickie.linke@horizonspost.com',
                           'myasnikovaahu1981@list.ru',
                           'ziminayat1984@list.ru',
                           'gulyaevaulw1969@list.ru',
                           'panovauid1983@list.ru',
                           'polyakovamoz1968@list.ru',
                           'lukinalep1985@list.ru',
                           'fomichyovazoq1966@list.ru',
                           'efremovaokg1973@list.ru',
                           'lg0s2o7o@maxamba.com',
                           'yakushevawns1997@list.ru',
                           'evdokimovakje1983@list.ru',
                           'qkuvbmjstz@rambler.ru',
                           'kovalyovanoa1978@list.ru',
                           'borisovaamn1966@list.ru',
                           'nosovaher1986@list.ru',
                           'nadeen.scotto@allwebemails.com',
                           'kabanovaolx1988@list.ru',
                           'wyfyspan@maxamba.com',
                           'kozlovazjp1972@list.ru',
                           'lytkinaulg1975@list.ru',
                           'dbyonvksxa@rambler.ru',
                           'afanasevahvh1978@list.ru',
                           'shashkovaagj1975@list.ru',
                           'rdmy9llc@maxamba.com',
                           'novikovafss1987@list.ru',
                           'grigorevaofd1996@list.ru',
                           'ilinaaaz1987@list.ru',
                           'zakharovaqho1969@list.ru',
                           'volkovagrj1988@list.ru',
                           'karpovairs1977@list.ru',
                           'vyfbqszynh@rambler.ru',
                           'montray.rosenburg@mailmagnet.co',
                           'o52cq8f6@maxamba.com',
                           'biryukovavnt1968@list.ru',
                           'kolobovatxa1968@list.ru',
                           'nikitinadav1979@list.ru',
                           'shcherbakovazda1979@list.ru',
                           'wqzveaqzxo@rambler.ru',
                           'savinawsy1995@list.ru',
                           'zuevatnd1980@list.ru',
                           'pakhomovaxia1997@list.ru',
                           'dorofeevacfy1995@list.ru',
                           'eliseevafma1986@list.ru',
                           'owpyubuw@maxamba.com',
                           'ironesha.hard@allfreemail.net',
                           'shestakovansi1970@list.ru',
                           'potapovaajt1978@list.ru',
                           'khokhlovajal1985@list.ru',
                           'lrymlpauey@rambler.ru',
                           'zhdanovaizi1984@list.ru',
                           'popovaoaz1973@list.ru',
                           'vorontsovatrd1986@list.ru',
                           'bobrovapts1992@list.ru',
                           'pbfh1d57@maxamba.com',
                           'dyachkovawji1972@list.ru',
                           'evdokimovagxu1980@list.ru',
                           'iwozyekuwk@rambler.ru',
                           'belyaevafvs1995@list.ru',
                           'lavrentevalac1994@list.ru',
                           'belozyorovazpk1972@list.ru',
                           'stepanovaczg1986@list.ru',
                           'zinovevavdl1991@list.ru',
                           'dmitrievafns1966@list.ru',
                           'rusakovauoy1977@list.ru',
                           'nalaiyah.mellor@openmail.pro',
                           'biryukovaxjc1970@list.ru',
                           'fyodorovahjz1992@list.ru',
                           'makarovaemx1989@list.ru',
                           'yakovlevaojb1993@list.ru',
                           'ustinovanuo1973@list.ru',
                           'sazonovavoo1969@list.ru',
                           'shashkovadeh1982@list.ru',
                           'lavrentevamvg1987@list.ru',
                           'kenley.folkerts@easymailer.live',
                           'mikhaylovaxvl1968@list.ru',
                           'egorovarzn1967@list.ru',
                           'likhachyovamud1970@list.ru',
                           'drozdovahwt1968@list.ru',
                           'sukhanovahpm1980@list.ru',
                           'bespalovaspe1980@list.ru',
                           'lytkinaiuh1996@list.ru',
                           'karpovatsv1985@list.ru',
                           'sahira.risch@easymailer.live',
                           'odintsovaucf1984@list.ru',
                           'alekseevadya1985@list.ru',
                           'zinovevanoh1974@list.ru',
                           'orekhovangf1976@list.ru',
                           'lebedevacwk1993@list.ru',
                           'teterinabzf1983@list.ru',
                           'chernovaqjk1971@list.ru',
                           'novikovaest1979@list.ru',
                           'kt3zt7ud@maxamba.com',
                           'rogovapft1994@list.ru',
                           'yakushevawfs1969@list.ru',
                           'gromovawvg1975@list.ru',
                           'lukinappo1975@list.ru',
                           'iy7xxu6h@maxamba.com',
                           'vinogradovaoli1975@list.ru',
                           'samoylovaxlr1994@list.ru',
                           'molchanovavmi1973@list.ru',
                           'yakushevacih1984@list.ru',
                           'trelen.schaar@mailmagnet.co',
                           'solovyovaqug1995@list.ru',
                           'samoylovamzz1984@list.ru',
                           'semyonovamvs1987@list.ru',
                           'merkushevawvv1991@list.ru',
                           'i2wfmtop@maxamba.com',
                           'komissarovakit1995@list.ru',
                           'kondratevagnm1981@list.ru',
                           'shashkovayzd1972@list.ru',
                           'orlovazwu1978@list.ru',
                           'jzyxpbj0@maxamba.com',
                           'isaevagdp1976@list.ru',
                           'sokolovaoar1982@list.ru',
                           'drozdovaile1971@list.ru',
                           'gs99c6nw@maxamba.com',
                           'zhuravlyovadkk1970@list.ru',
                           'kanisha.suppa@inboxorigin.com',
                           'tikhonovappg1981@list.ru',
                           'sofiyayudina4159@list.ru',
                           'kostinazag1968@list.ru',
                           'ebpgpfzgzw@rambler.ru',
                           'tikhonovazpw1967@list.ru',
                           'strelkovaikm1991@list.ru',
                           'hb420733@maxamba.com',
                           'potapovalfe1979@list.ru',
                           'sobolevaphs1993@list.ru',
                           'doroninamwa1973@list.ru',
                           'artemevabpi1974@list.ru',
                           'ershovaiso1973@list.ru',
                           'turovaelvida4918@list.ru',
                           'tuyqtmotmk@rambler.ru',
                           'karpovanmv1990@list.ru',
                           'shchukinaiyo1993@list.ru',
                           'morgane.mcclendon@allwebemails.com',
                           'titovahyo1994@list.ru',
                           '9zekk24z@maxamba.com',
                           'antonovaixe1980@list.ru',
                           'samsonovapel1976@list.ru',
                           'ignatovavnp1973@list.ru',
                           'odintsovaujq1971@list.ru',
                           'mismciqbdo@rambler.ru',
                           'lazarevaadp1992@list.ru',
                           'subbotinaiam1969@list.ru',
                           'korolyovauea1996@list.ru',
                           'panovarzs1968@list.ru',
                           'sazonovahga1993@list.ru',
                           '08bwi5v8@maxamba.com',
                           'sergeevazdo1982@list.ru',
                           'rachiel.bowker@allwebemails.com',
                           'nikonovatvv1985@list.ru',
                           'mvcugrnh@maxamba.com',
                           'lazarevaxrd1980@list.ru',
                           'davydovakmt1993@list.ru',
                           'kapustinaqbq1996@list.ru',
                           'samsonovalaw1976@list.ru',
                           'yuledemyshev1994@list.ru',
                           'w1enhiw2@maxamba.com',
                           'samsonovainl1979@list.ru',
                           'dyachkovavwz1971@list.ru',
                           'bolshakovayub1993@list.ru',
                           'f9yg6yjr@maxamba.com',
                           'moiseevajsq1997@list.ru',
                           'gorshkovakhm1979@list.ru',
                           'savelevaijf1990@list.ru',
                           'kulaginaaut1974@list.ru',
                           'petie.dalke@mailmagnet.co',
                           '9e5nw0fs@maxamba.com',
                           'evseevajuy1971@list.ru',
                           'tarasovairn1967@list.ru',
                           'v0dj8vc2@maxamba.com',
                           'mamontovaeeo1971@list.ru',
                           'romanovasez1992@list.ru',
                           'romanovapgr1997@list.ru',
                           'u9i4j90k@maxamba.com',
                           'konstantinovamxm1995@list.ru',
                           'davydovapre1996@list.ru',
                           'lytkinawbr1990@list.ru',
                           'n2k2cd41@maxamba.com',
                           'kulakovatlw1976@list.ru',
                           'voronovabsd1974@list.ru',
                           'yakovlevazbl1987@list.ru',
                           'khailey.whelchel@allwebemails.com',
                           'r9ep44du@maxamba.com',
                           'kulikovaljk1984@list.ru',
                           'kazakovakdr1989@list.ru',
                           'ermakovanwm1969@list.ru',
                           '0mopvwlw@maxamba.com',
                           'tikhonovaezx1972@list.ru',
                           'shiryaevafff1997@list.ru',
                           'savelevajwe1970@list.ru',
                           'stepanovadro1975@list.ru',
                           '5gbbte35@maxamba.com',
                           'vasilevacun1971@list.ru',
                           'danilovazye1980@list.ru',
                           'trofimovaegi1970@list.ru',
                           '0rde94jz@maxamba.com',
                           'prerna.choiniere@horizonspost.com',
                           'eliseevajbz1985@list.ru',
                           'euictavl@maxamba.com',
                           'lebedevaxpc1969@list.ru',
                           'fomichyovacfg1984@list.ru',
                           'filatovacfk1987@list.ru',
                           'kalashnikovawsk1966@list.ru',
                           'fcjg7y3u@maxamba.com',
                           'hj4ibctd@maxamba.com',
                           'sobolevafqf1978@list.ru',
                           'egorovavjf1967@list.ru',
                           '1wq9gpze@maxamba.com',
                           'kolesnikovaypa1987@list.ru',
                           'v2udv21u@maxamba.com',
                           'moiseevamhn1982@list.ru',
                           'rodionovatec1995@list.ru',
                           'rogovapej1981@list.ru',
                           'solovyovapfv1987@list.ru',
                           'teterinalbk1982@list.ru',
                           'molika.richey@mailmagnet.co',
                           'voronovafny1979@list.ru',
                           'bew81cw2@maxamba.com',
                           'kulikovaocv1979@list.ru',
                           'efremovafov1982@list.ru',
                           'gejnw8sk@maxamba.com',
                           'fomichyovaidi1993@list.ru',
                           'melnikovajfx1971@list.ru',
                           '01jkw5jp@maxamba.com',
                           'ustinovabds1989@list.ru',
                           'danilovaqhg1987@list.ru',
                           'kbmf2dak@maxamba.com',
                           'knyazevaewc1989@list.ru',
                           'p4imn7dg@maxamba.com',
                           'blinovahoa1987@list.ru',
                           'zhuravlyovafmj1977@list.ru',
                           'eizan.weidemann@horizonspost.com',
                           'davydovaohb1966@list.ru',
                           't448hbtt@maxamba.com',
                           'shcherbakovaxhm1994@list.ru',
                           'likhachyovaods1967@list.ru',
                           'omv3ivwc@maxamba.com',
                           'kulikovarnl1967@list.ru',
                           'egorovajqr1978@list.ru',
                           '9udv7klg@maxamba.com',
                           'zykovaegg1987@list.ru',
                           'tynfzjab@maxamba.com',
                           'howard.herzberg@inboxorigin.com',
                           'frolovalsx1997@list.ru',
                           'vnzk74yx@maxamba.com',
                           'kulakovavmz1973@list.ru',
                           '57yyxe70@maxamba.com',
                           'kopylovawlf1997@list.ru',
                           'filatovawwf1975@list.ru',
                           'doroninavaa1978@list.ru',
                           'eqd5qpzr@maxamba.com',
                           'f8fe1a08bd@emailfoxi.pro',
                           '6kgubpx3@maxamba.com',
                           'darlenis.schnell@allfreemail.net',
                           'kulaginanue1968@list.ru',
                           'e55c568163@emailfoxi.pro',
                           'makarovaxkw1976@list.ru',
                           'muravyovamvq1994@list.ru',
                           'medvedevaxxj1977@list.ru',
                           'kapustinatbc1993@list.ru',
                           'vlasovands1992@list.ru',
                           '802f6734fe@emailfoxi.pro',
                           'veselovayca1982@list.ru',
                           'lkuy0ckc@maxamba.com',
                           'hkeccglnxlkicv@mynanaimohomes.com',
                           'donye.ingraham@mailmagnet.co',
                           'orlovaeot1996@list.ru',
                           'seleznyovaucd1975@list.ru',
                           'i045zmkw@maxamba.com',
                           'rodionovayxg1966@list.ru',
                           'fxqkxk@mynanaimohomes.com',
                           'uvarovansm1985@list.ru',
                           'nazarovailt1978@list.ru',
                           'polyakovaadj1981@list.ru',
                           '96lqcdwq@maxamba.com',
                           'uvarovavms1988@list.ru',
                           'markovaqrt1989@list.ru',
                           '64v9pqfk@maxamba.com',
                           'dkadnegqydj@maxamba.com',
                           'ggh5y56q@maxamba.com',
                           'asheena.brobst@mailmagnet.co',
                           'pestovacao1986@list.ru',
                           'yoktexrm@maxamba.com',
                           'r11k3vdj@maxamba.com',
                           'kolesnikovandt1967@list.ru',
                           'nmtefnkzka@maxamba.com',
                           'lobanovazoc1982@list.ru',
                           'vda42yx4@maxamba.com',
                           'bykovasgn1977@list.ru',
                           'aneel.rempel@solarnyx.com',
                           'zj2dhj8z@maxamba.com',
                           'matveevajkm1985@list.ru',
                           't7rn02yj@maxamba.com',
                           'ponomaryovaoir1970@list.ru',
                           'wttwrixaqvcigps@maxamba.com',
                           'e50n0jz9@maxamba.com',
                           'novikovaahv1987@list.ru',
                           'volkovarxk1981@list.ru',
                           'ershovavwn1971@list.ru',
                           'mukhinaoet1989@list.ru',
                           '9p5gh93d@maxamba.com',
                           'seleznyovasyy1987@list.ru',
                           'flzrtopemzuwvwr@muatoc.com',
                           'abramovaxtw1973@list.ru',
                           'melnikovayhf1992@list.ru',
                           'kalininatrl1966@list.ru',
                           'evmgvgx@maxamba.com',
                           'gorshkovadzp1967@list.ru',
                           'rodionovaurz1993@list.ru',
                           'ermakovafbj1979@list.ru',
                           'markovagtn1992@list.ru',
                           'aleksandrovakmd1970@list.ru',
                           'ymlmel@muatoc.com',
                           'sukhanovaftx1996@list.ru',
                           'nikonovaoiz1990@list.ru',
                           'sazonovayfa1983@list.ru',
                           'rusakovasql1972@list.ru',
                           'agafonovasui1977@list.ru',
                           'zdqcwr@miteon.com',
                           'bobylyovaepb1991@list.ru',
                           'likhachyovacif1992@list.ru',
                           'odintsovaqof1967@list.ru',
                           'loginovatid1985@list.ru',
                           'pjrkslqmlmuckb@maxamba.com',
                           'danilovaauh1991@list.ru',
                           'gavrilovaabs1994@list.ru',
                           'onufrii806vinogradov1983@list.ru',
                           'markovatmx1986@list.ru',
                           'belyaevacgr1967@list.ru',
                           'uvarovasgc1973@list.ru',
                           '8eda26e2c9@emailfoxi.pro',
                           'wvfjhfmwa@miteon.com',
                           'mishinabsk1970@list.ru',
                           'noskovawsw1989@list.ru',
                           'belousovacnv1990@list.ru',
                           'wtlipityty@nespressopixie.com',
                           'fokinapex1979@list.ru',
                           '20263070d0@emailfoxi.pro',
                           'gurevamhb1986@list.ru',
                           'antonovafnr1979@list.ru',
                           'ryabovabki1974@list.ru',
                           'wcshnnq@muatoc.com',
                           '1f2db77132@emailfoxi.pro',
                           'kiselyovacpk1986@list.ru',
                           'gordeevabys1971@list.ru',
                           'nikolaevayie1976@list.ru',
                           'fckgehkklvwk@maxamba.com',
                           'sysoevaete1992@list.ru',
                           'dementevafzi1968@list.ru',
                           '0c42f0510d@emailfoxi.pro',
                           'samoylovagnp1967@list.ru',
                           'gavrilovajbv1974@list.ru',
                           'ythfrnjwwkdeq@muatoc.com',
                           'evdokimovayfp1991@list.ru',
                           'de1eec9f96@emailfoxi.pro',
                           'safonovaspk1968@list.ru',
                           'vladimirovagdu1975@list.ru',
                           'vvckziu@miteon.com',
                           'mikhaylovajtr1982@list.ru',
                           'yakushevakiu1967@list.ru',
                           'savinajlt1975@list.ru',
                           'b696b2a462@emailfoxi.pro',
                           'urkgnrknukbbw@maxamba.com',
                           'tsvetkovawdw1970@list.ru',
                           'kirillovakdj1988@list.ru',
                           'nikitinasep1980@list.ru',
                           'vlbnzg@mynanaimohomes.com',
                           '4e287acf39@emailfoxi.pro',
                           'sharapovagbj1973@list.ru',
                           'ziminaojh1969@list.ru',
                           'shcherbakovadox1980@list.ru',
                           'lavrentevavuk1980@list.ru',
                           'hkxlsenvvt@muatoc.com',
                           'a30edd2044@emailfoxi.pro',
                           'kulikovazsf1978@list.ru',
                           'khokhlovaffw1992@list.ru',
                           'belovawtg1978@list.ru',
                           'wuokoczvpclo@miteon.com',
                           'konovalovampn1975@list.ru',
                           'molchanovaeve1988@list.ru',
                           'zykovawga1995@list.ru',
                           'ab24ec5552@emailfoxi.pro',
                           'wimamkhyr@mynanaimohomes.com',
                           'popovajzf1984@list.ru',
                           'likhachyovawoq1969@list.ru',
                           'vlwpbvzhobzln@maxamba.com',
                           'yudinnuriman894562@list.ru',
                           'e2fd8b32b8@emailfoxi.pro',
                           'lobanovamdr1975@list.ru',
                           'rsarnljynv@miteon.com',
                           'avdeevautl1994@list.ru',
                           'subbotinaefk1971@list.ru',
                           'ershovahyp1994@list.ru',
                           'nikonovazri1985@list.ru',
                           'terentevazyw1988@list.ru',
                           'ihyfnozv@mynanaimohomes.com',
                           'a1cfbd3771@emailfoxi.pro',
                           'lukinaeja1985@list.ru',
                           'iffkszvpyww@muatoc.com',
                           'dorofeevaclo1972@list.ru',
                           'orlovaiyf1987@list.ru',
                           'd6f722c950@emailfoxi.pro',
                           'merkushevanjo1997@list.ru',
                           'kondratevaejw1989@list.ru',
                           'romanovaofc1995@list.ru',
                           'bljkypybgrbx@miteon.com',
                           'kovalyovasje1981@list.ru',
                           'ilinapwh1997@list.ru',
                           'semyonovadoq1991@list.ru',
                           'kowzpoay@nespressopixie.com',
                           'petrovajcj1971@list.ru',
                           'lapinague1976@list.ru',
                           'andreevangc1983@list.ru',
                           'rozhkovatwg1990@list.ru',
                           'kolobovaigp1984@list.ru',
                           'dfjyrwrjb@nespressopixie.com',
                           'mamontovanxn1983@list.ru',
                           'mikheevarge1976@list.ru',
                           'georgievafeia946@list.ru',
                           'odifqedgdwmabgc@nespressopixie.com',
                           'tretyakovaqpn1993@list.ru',
                           'kozlovakrn1990@list.ru',
                           'sorokinacqj1995@list.ru',
                           'kowfbgib@nespressopixie.com',
                           'baranovaieu1990@list.ru',
                           'maksimovaaeu1966@list.ru',
                           'ershovaswh1983@list.ru',
                           'mukhinajer1983@list.ru',
                           '6dc9509ced@emailfoxi.pro',
                           'timofeevabnx1991@list.ru',
                           'hwcvjldvutp@muatoc.com',
                           'sazonovayqx1980@list.ru',
                           'b0f45cdf05@emailfoxi.pro',
                           'fwchdte@maxamba.com',
                           'gordeevaxae1970@list.ru',
                           'matveevaodt1993@list.ru',
                           'loginovaxzq1992@list.ru',
                           'pxiuiye@nespressopixie.com',
                           'nesterovagxq1987@list.ru',
                           'a8e184806d@emailfoxi.pro',
                           'smirnovaxtb1973@list.ru',
                           'medvedevaejx1967@list.ru',
                           'myasnikovajpz1993@list.ru',
                           'utwzrqzxe@miteon.com',
                           'sidorovahdg1984@list.ru',
                           'rybakovangv1981@list.ru',
                           '0b5cfb2801@emailfoxi.pro',
                           'nosovalcy1986@list.ru',
                           'sharapovdometii1983@list.ru',
                           'burovasui1983@list.ru',
                           'fvwhiopqed@miteon.com',
                           'ziminaoco1994@list.ru',
                           'lapinaicm1989@list.ru',
                           'aleksandrovahdn1992@list.ru',
                           'konovalovabvt1990@list.ru',
                           'cbjbeuluuicr@maxamba.com',
                           '0e40ddc095@emailfoxi.pro',
                           'kondratevaqnz1991@list.ru',
                           'molchanovarbk1969@list.ru',
                           'crzagajrifp@maxamba.com',
                           'egorovajty1978@list.ru',
                           '989360689b@emailfoxi.pro',
                           'bogdanovaoaz1975@list.ru',
                           'timofeevatrd1989@list.ru',
                           'kopylovawll1981@list.ru',
                           'ashkirw@mynanaimohomes.com',
                           'gorbunovavanda8698@list.ru',
                           'stepanovavcw1990@list.ru',
                           'orekhovahtr1981@list.ru',
                           'sysoevacic1970@list.ru',
                           'tknicpi@nespressopixie.com',
                           'fadeevsabir89@list.ru',
                           '12d8423eef@emailfoxi.pro',
                           'shashkovaknw1996@list.ru',
                           'moiseevaexm1966@list.ru',
                           'kulikovaqtg1969@list.ru',
                           'iaknxiglhmj@maxamba.com',
                           'zinovevanda1997@list.ru',
                           'ada3dc0c0a@emailfoxi.pro',
                           'abramovagom1970@list.ru',
                           'gerasimovalfy1984@list.ru',
                           'bobylyovaibp1975@list.ru',
                           'suvorovapck1985@list.ru',
                           'qvgjyxblbdzrut@maxamba.com',
                           'nofevh53@maxamba.com',
                           'rvfvwvh@nespressopixie.com',
                           '2ee5025e4e@emailfoxi.pro',
                           'ujj4z8iu@maxamba.com',
                           'mishinavvy1995@list.ru',
                           'ziminaebc1979@list.ru',
                           'belousovacue1981@list.ru',
                           'np10gpq8@maxamba.com',
                           'likhachyovaszo1981@list.ru',
                           'turovazyz1996@list.ru',
                           'vofpopywcrqo@maxamba.com',
                           'g8074amx@maxamba.com',
                           '0826703272@emailfoxi.pro',
                           '1rfd04g1@maxamba.com',
                           'borisovakdp1975@list.ru',
                           'matveevazba1990@list.ru',
                           'ilinapdo1997@list.ru',
                           'kudrbiii@nespressopixie.com',
                           'cthcugd3@maxamba.com',
                           'moyiqdjd@maxamba.com',
                           'dyachkovatlx1982@list.ru',
                           'qidigz@mynanaimohomes.com',
                           'kuznetsovatfx1995@list.ru',
                           'r8r1hsop@maxamba.com',
                           'tikhonovatby1996@list.ru',
                           '911d1d68d7@emailfoxi.pro',
                           's0eef3yb@maxamba.com',
                           'mikhaylovatwg1981@list.ru',
                           'konstantinovasfd1968@list.ru',
                           'pljrbuoojnw@muatoc.com',
                           'r9oaoy64@maxamba.com',
                           'py3edcua@maxamba.com',
                           'maslovaysc1984@list.ru',
                           '8f645c4dcf@emailfoxi.pro',
                           'vgtyhaehj@maxamba.com',
                           'zvqjenen@maxamba.com',
                           'osipovajqv1967@list.ru',
                           'semyonovaeqm1988@list.ru',
                           'kalashnikovaxbw1972@list.ru',
                           'medvedevapeh1980@list.ru',
                           '0fc7410daa@emailfoxi.pro',
                           'fedotovamja1988@list.ru',
                           '5ana2nso@maxamba.com',
                           'vishnyakovaicy1997@list.ru',
                           'sfcdfadn@muatoc.com',
                           'avdeevaunq1966@list.ru',
                           'kovalyovaopb1994@list.ru',
                           'wts84bh7@maxamba.com',
                           'mcg0v5mn@maxamba.com',
                           'gldegrlgtooknf@miteon.com',
                           '03daba3310@emailfoxi.pro',
                           'jtvjnbfa@maxamba.com',
                           'kotovawmc1988@list.ru',
                           'b6wpaqvm@maxamba.com',
                           'fcxagdii@maxamba.com',
                           'solovyovadcm1973@list.ru',
                           'orekhovajem1976@list.ru',
                           'nesterovaeir1966@list.ru',
                           'mqsgxtnz@maxamba.com',
                           'c94af648b1@emailfoxi.pro',
                           'kryukovampn1977@list.ru',
                           'stepanovadkg1968@list.ru',
                           'xyymvz9a@maxamba.com',
                           'ougchtu@mynanaimohomes.com',
                           'zuevanfr1987@list.ru',
                           'jakpdrcb@maxamba.com',
                           'f2f6567b73@emailfoxi.pro',
                           'ivanovabtf1975@list.ru',
                           '91yd2idh@maxamba.com',
                           'gavrilovansj1968@list.ru',
                           'komarovaymh1969@list.ru',
                           'oxkwcjoujlrcbp@mynanaimohomes.com',
                           'x7pd7pgy@maxamba.com',
                           'zhukovazsq1979@list.ru',
                           'lebedevazxz1993@list.ru',
                           'yt8okspa@maxamba.com',
                           'abramovasso1980@list.ru',
                           '7ita601b@maxamba.com',
                           'gorbunovaqdw1979@list.ru',
                           '3bf1d6da6e@emailfoxi.pro',
                           'yabfrkrrxzw@maxamba.com',
                           'afanasevafyv1969@list.ru',
                           'kozlovahrg1983@list.ru',
                           'rvzvttce@maxamba.com',
                           'ngy7xwqs@maxamba.com',
                           'zaputvi@mynanaimohomes.com',
                           '3wr0ar8a@maxamba.com',
                           'd6c1a892e2@emailfoxi.pro',
                           'maksimovaudl1979@list.ru',
                           'nazarovalfr1990@list.ru',
                           'shcherbakovafgg1997@list.ru',
                           '4lwyeqy5@maxamba.com',
                           'dementevarkj1974@list.ru',
                           'nosovapwz1967@list.ru',
                           'wwaztjjfcumsi@maxamba.com',
                           'kp418jq7@maxamba.com',
                           '8tejsun9@maxamba.com',
                           'rybakovaqlj1994@list.ru',
                           'kapustinavbz1997@list.ru',
                           'artemevajcp1971@list.ru',
                           '7liebvlt@maxamba.com',
                           'fyodorovavae1992@list.ru',
                           'mhbzzkd@nespressopixie.com',
                           'fedotovaiky1966@list.ru',
                           'mnxda544@maxamba.com',
                           'fb4l2ug1@maxamba.com',
                           'doroninafhk1991@list.ru',
                           'khltwwuaggbzr@miteon.com',
                           'popovamgp1979@list.ru',
                           'ugontmp7@maxamba.com',
                           'ghnnf777@maxamba.com',
                           'belovahvw1984@list.ru',
                           'rybakovacrd1966@list.ru',
                           'komissarovawkd1996@list.ru',
                           'klrathnutfrt@maxamba.com',
                           'qssudf18@maxamba.com',
                           'medvedevahvu1966@list.ru',
                           'romanovayuzefa1997@list.ru',
                           'n8tj5w5h@maxamba.com',
                           'denisovavxo1974@list.ru',
                           'gorbunovampl1987@list.ru',
                           'ugzmgbat@mynanaimohomes.com',
                           'lrst8xhp@maxamba.com',
                           'anisimovauhu1994@list.ru',
                           'egorovaqph1967@list.ru',
                           'lk7vma3f@maxamba.com',
                           'bwptgojcyekpejn@nespressopixie.com',
                           'ky0dep22@maxamba.com',
                           'vorontsovawsr1976@list.ru',
                           '7qjy95nx@maxamba.com',
                           'seliverstovavyc1981@list.ru',
                           'zakharovavur1967@list.ru',
                           'invgruas@maxamba.com',
                           'nikonovayqm1995@list.ru',
                           'mbafjkru@muatoc.com',
                           'larionovavzk1980@list.ru',
                           'vishnyakovahxg1997@list.ru',
                           'bejsbjfh@maxamba.com',
                           'mdn846rv@maxamba.com',
                           'moiseevahlk1969@list.ru',
                           'egorovapco1997@list.ru',
                           'kolesnikovarkr1970@list.ru',
                           'tsirlspb@nespressopixie.com',
                           'sabellamckne6@list.ru',
                           'rj9xtsdq@maxamba.com',
                           'dfe0d63f1f@emailfoxi.pro',
                           '6jc1j6k0@maxamba.com',
                           'sxekfodnqesf@miteon.com',
                           'zhdanovagzm1986@list.ru',
                           'aleksandrovawwn1976@list.ru',
                           'dr5l14lu@maxamba.com',
                           'nikonovakwq1994@list.ru',
                           'smbng6lx@maxamba.com',
                           'efdc64bb7b@emailfoxi.pro',
                           'oibnvqnnuqmaj@miteon.com',
                           'w4s41l55@maxamba.com',
                           'vorobyovayet1990@list.ru',
                           'fominaqfe1968@list.ru',
                           'wzjqhyov@maxamba.com',
                           'dyachkovadxt1986@list.ru',
                           '9ab09b8d06@emailfoxi.pro',
                           'xbarqlaw@maxamba.com',
                           'evfpdink@miteon.com',
                           'gavrilovapsn1968@list.ru',
                           'veselovaxjr1988@list.ru',
                           'jkjnmat3@maxamba.com',
                           'tampa.victorino@openmail.pro',
                           'vorobyovaxbo1991@list.ru',
                           'zhukovamud1981@list.ru',
                           'iupvh0sb@maxamba.com',
                           'medvedevagjo1967@list.ru',
                           'gfstaqyplmsx@mynanaimohomes.com',
                           '97d57198d0@emailfoxi.pro',
                           'lk0xfnqd@maxamba.com',
                           'orlovaixy1968@list.ru',
                           'antonovahkk1988@list.ru',
                           'w2q9vmcb@maxamba.com',
                           'fokinavdt1981@list.ru',
                           'mukhinalat1997@list.ru',
                           'ur6opizy@maxamba.com',
                           'sinayhir@mynanaimohomes.com',
                           '66c6966701@emailfoxi.pro',
                           'sorokinaqbb1991@list.ru',
                           '14vn2yei@maxamba.com',
                           'danney.blom@allfreemail.net',
                           'bykovatpv1973@list.ru',
                           '65ydsi8g@maxamba.com',
                           'y9rqc68o@maxamba.com',
                           'a675e6307e@emailfoxi.pro',
                           'fcfrdmlarqlftlk@mynanaimohomes.com',
                           'efimovackd1980@list.ru',
                           'solovyovaoqw1972@list.ru',
                           'qb86fa0s@maxamba.com',
                           'zhuravlyovafut1976@list.ru',
                           'fomichyovaetx1986@list.ru',
                           'gustavkudryavcev1984@list.ru',
                           'evseevajfl1994@list.ru',
                           '90g19b6i@maxamba.com',
                           'nadyah.bezanson@easymailer.live',
                           'raprnotu@miteon.com',
                           '4ab6eb56f8@emailfoxi.pro',
                           'dypcxkr3@maxamba.com',
                           '51281ncu@maxamba.com',
                           'petukhovamqe1966@list.ru',
                           'aksyonovazzf1974@list.ru',
                           'koshelevazin1975@list.ru',
                           'csdfqmjubqwgve@list.ru',
                           'zinovevanht1984@list.ru',
                           'miz4e5dm@maxamba.com',
                           'xmteocdkpapcnq@mynanaimohomes.com',
                           'shestakovaxbx1976@list.ru',
                           'c82f283d00@emailfoxi.pro',
                           't5bymfjw@maxamba.com',
                           'juhee.ferber@easymailer.live',
                           'rz6lyx3k@maxamba.com',
                           'tovvchblko@mynanaimohomes.com',
                           'belovawlq1993@list.ru',
                           '8avcpnwv@maxamba.com',
                           '9c5a72f9ae@emailfoxi.pro',
                           'zhdanovabmw1991@list.ru',
                           'nazarovahti1971@list.ru',
                           'nxpzynn3@maxamba.com',
                           'suvorovamls1996@list.ru',
                           'dqmcbns@maxamba.com',
                           'qhkjhz9v@maxamba.com',
                           'kudryavtsevabrz1966@list.ru',
                           'molchanovarmx1990@list.ru',
                           'abramovapao1987@list.ru',
                           'jurie.burrier@inboxorigin.com',
                           'c8d83e3870@emailfoxi.pro',
                           'qsdxziw8@maxamba.com',
                           'gorshkovakhd1997@list.ru',
                           'fpafjlgf@maxamba.com',
                           'knyazevatdv1977@list.ru',
                           'sitnikovafum1985@list.ru',
                           'sr88s0on@maxamba.com',
                           'kuznetsovakwd1977@list.ru',
                           'nikiforovagnd1974@list.ru',
                           'matveevadvv1985@list.ru',
                           'seleznyovaall1981@list.ru',
                           'gromovaxwd1971@list.ru',
                           'fedoseevalkz1969@list.ru',
                           'dmitrievagfb1985@list.ru',
                           'sorokinatqm1992@list.ru',
                           'vorobyovauha1970@list.ru',
                           'nikiforovaytn1982@list.ru',
                           'moiseevahen1967@list.ru',
                           'bmspzzttmcm@nespressopixie.com',
                           'timofeevavcs1995@list.ru',
                           'kopylovajlg1982@list.ru',
                           'lytkinacfj1978@list.ru',
                           'rodionovamjm1969@list.ru',
                           'belovadvr1986@list.ru',
                           'iqcldaaitfgblp@nespressopixie.com',
                           'emelyanovaajr1996@list.ru',
                           'uvarovaqpl1977@list.ru',
                           'nesterovatro1987@list.ru',
                           'rybakovaxzt1981@list.ru',
                           'kostinabwp1988@list.ru',
                           'bobylyovamdh1972@list.ru',
                           'anisimovakhl1981@list.ru',
                           'vkucnyv@mailto.plus',
                           'hisutyaohmzgf@miteon.com',
                           'samoylovahea1997@list.ru',
                           'zddachoooeplpj@mynanaimohomes.com',
                           'dementevabhm1983@list.ru',
                           'heqcosrjznn@mynanaimohomes.com',
                           'kryukovaaog1987@list.ru',
                           'dmitrievagsm1989@list.ru',
                           'qiallrmeafeilsc@nespressopixie.com',
                           'morkjgnqmnv@mynanaimohomes.com',
                           'mukhinasza1974@list.ru',
                           'nazarovakfg1990@list.ru',
                           'tikhonovalgk1970@list.ru',
                           'afanasevaxle1966@list.ru',
                           'gromovacye1985@list.ru',
                           'borisovaqco1981@list.ru',
                           'nikolaevakcn1973@list.ru',
                           'fominayri1971@list.ru',
                           'alekseevamlu1984@list.ru',
                           'titovajif1987@list.ru',
                           'seliverstovagxh1986@list.ru',
                           'gorshkovatbr1992@list.ru',
                           'prokhorovakwo1970@list.ru',
                           'isakovauef1972@list.ru',
                           'voronovacsq1972@list.ru',
                           'zhdanovavsw1974@list.ru',
                           'yakovlevahyw1978@list.ru',
                           'korolyovafyr1993@list.ru',
                           'maslovapue1976@list.ru',
                           'safonovasbp1972@list.ru',
                           'maksimovaqzl1973@list.ru',
                           'zinovevarpx1983@list.ru',
                           'jfdblzfraq@mynanaimohomes.com',
                           'dviadp@mynanaimohomes.com',
                           'sevenyearolddevi@trezy.online',
                           'm4l5zife@vncctv.org',
                           'trenton_bogan890@gerix.org',
                           'sfmnsitmbadf@mynanaimohomes.com',
                           'zgasca@mailto.plus',
                           'tmtfj@rustyload.com',
                           'blushmany@rustyload.com',
                           'trofimovarvd1971@list.ru',
                           'gavrilovajou1991@list.ru',
                           'fadeevacpw1977@list.ru',
                           'anisimovabon1996@list.ru',
                           'mikhaylovardc1987@list.ru',
                           'korolyovabde1969@list.ru',
                           'fadeevamnq1971@list.ru',
                           'kabanovaevm1978@list.ru',
                           'huhwkk@miteon.com',
                           'wpcausbsfpohhr@maxamba.com',
                           'arha.heidrick@openmail.pro',
                           'hqfpesstiq@muatoc.com',
                           'fyodorovatft1978@list.ru',
                           'zykovaxuv1968@list.ru',
                           'korolyovadfr1978@list.ru',
                           'sitnikovauuj1980@list.ru',
                           'azaytseva@ymail.com',
                           'konstantinovafgg1966@list.ru',
                           'dorofeevamwk1971@list.ru',
                           'abramovapzl1982@list.ru',
                           'fyodorovazda1975@list.ru',
                           'dementevagqj1994@list.ru',
                           'wmmuk@any.pink',
                           'zakyfhbpaelax@muatoc.com',
                           'fxiud@rustyload.com',
                           'xcyeuvmgisokfeg@mynanaimohomes.com',
                           'tudniczhn2@cmdkl.com',
                           'sharapovazck1966@list.ru',
                           'artemevaabq1991@list.ru',
                           'dementevasij1973@list.ru',
                           'moiseevaqhy1977@list.ru',
                           'belovapda1996@list.ru',
                           'ivanovafzf1982@list.ru',
                           'popovarwp1972@list.ru',
                           'krylovapdd1985@list.ru',
                           'kolesnikovavfk1973@list.ru',
                           'belyakovavsh1984@list.ru',
                           'isakovabrh1985@list.ru',
                           '2710092dd18a@drmail.in',
                           'macabreethnicity@flaqua.site',
                           '87asleep@rustyload.com',
                           'dkvuswf@mynanaimohomes.com',
                           'yiloni2591@abevw.com',
                           '3132e31b82@emailfoxi.pro',
                           'vujocforh@muatoc.com',
                           'eduvv@mailto.plus',
                           'odxha@mailto.plus',
                           'combtmp+zr5qv@gmail.com',
                           'yoxuk@mailto.plus',
                           'akwhvqkshhsksvvv+reeve@gmail.com',
                           'capacitynmw+kiser@gmail.com',
                           'nesterovaenq1996@list.ru',
                           'antonovaqol1993@list.ru',
                           'myasnikovaldq1989@list.ru',
                           'filatovapxm1985@list.ru',
                           'grigorevayip1983@list.ru',
                           'sharapovatlt1985@list.ru',
                           'lobanovafvc1986@list.ru',
                           'xxvetk@mailto.plus',
                           'bulthuisavan+tidwell@googlemail.com',
                           'a.ka.g.gs.k.z.s.jd.vc.r@gmail.com',
                           'mamontovatbh1976@list.ru',
                           'e.li.xi.r.sd.g47@gmail.com',
                           'vorontsovanou1971@list.ru',
                           'rabk.s.b.vsh.d@gmail.com',
                           'sorokinauwh1995@list.ru',
                           'nikitinazze1978@list.ru',
                           'r.a.b.k.s.b.vs.hd@gmail.com',
                           'baranovasnm1978@list.ru',
                           'aleksandrovaitx1981@list.ru',
                           'sumihgaktar+waldrop@googlemail.com',
                           'silinalpi1993@list.ru',
                           'pavlovadyi1990@list.ru',
                           'shubinaazm1996@list.ru',
                           'ponomaryovabif1970@list.ru',
                           'zykovaytj1970@list.ru',
                           'pyxze@mailto.plus',
                           'stepanovazvo1997@list.ru',
                           'krasilnikovatnr1972@list.ru',
                           'agafonovaebe1974@list.ru',
                           'voronovasww1973@list.ru',
                           'so.phia.pa.rtp.wr.ggw@gmail.com',
                           'kondratevahjd1977@list.ru',
                           'konstantinovatbr1978@list.ru',
                           'medvedevakrl1967@list.ru',
                           'kolesnikovalpl1982@list.ru',
                           'ivanovamwf1975@list.ru',
                           'martynovawet1968@list.ru',
                           'fokinabfh1991@list.ru',
                           'nosovatoy1970@list.ru',
                           'sidorovacgj1976@list.ru',
                           'antonovanwt1988@list.ru',
                           'an.ichu.rm.uh.amma.d.a.6@gmail.com',
                           'kotovaihe1990@list.ru',
                           'orlovaksk1978@list.ru',
                           'andreevaarl1966@list.ru',
                           'aveqgu@mailto.plus',
                           'davydovaofo1975@list.ru',
                           'gulyaevaijd1990@list.ru',
                           'semyonovasbx1996@list.ru',
                           'sharovasnh1984@list.ru',
                           'fomichyovakor1981@list.ru',
                           'sharovaxef1984@list.ru',
                           'kornilovajep1989@list.ru',
                           'mironovasdm1982@list.ru',
                           'kulaginafba1990@list.ru',
                           'bogdanovatap1988@list.ru',
                           'voronovafqh1971@list.ru',
                           'kuzminaads1982@list.ru',
                           'zinovevavtu1983@list.ru',
                           'potapovalza1973@list.ru',
                           'egorovablw1980@list.ru',
                           'rusakovamvv1983@list.ru',
                           'blokhinadby1981@list.ru',
                           'nsakd@mailto.plus',
                           'lavrentevabdk1988@list.ru',
                           'mikhaylovaiyl1982@list.ru',
                           'mamontovahpl1984@list.ru',
                           'nikitinajcn1988@list.ru',
                           'isaevatcy1989@list.ru',
                           'shestakovaohb1996@list.ru',
                           'morozovafdy1981@list.ru',
                           'emelyanovatdx1980@list.ru',
                           'ilinavcl1992@list.ru',
                           'bespalovagjd1994@list.ru',
                           '0d9ddecea9@emailfoxi.pro',
                           'doroninaewo1986@list.ru',
                           'shashkovaidz1993@list.ru',
                           'potapovapqa1972@list.ru',
                           'rybakovadhv1996@list.ru',
                           '63801a6c8d@emailfoxi.pro',
                           'bespalovatuu1987@list.ru',
                           'fedotovamef1978@list.ru',
                           'doroninackf1988@list.ru',
                           'kiselyovawuf1988@list.ru',
                           'subbotinahdu1986@list.ru',
                           'lebedevaarn1968@list.ru',
                           'gorshkovadwn1973@list.ru',
                           'yakushevaocr1994@list.ru',
                           '0aea6bb160@emailfoxi.pro',
                           'ovchinnikovalxr1976@list.ru',
                           'myasnikovacsc1995@list.ru',
                           'mironovaucz1968@list.ru',
                           'chernovacky1983@list.ru',
                           'mishinayjy1992@list.ru',
                           'aleksandrovantw1997@list.ru',
                           'oyjyggn@mynanaimohomes.com',
                           '7f9395f344@emailfoxi.pro',
                           'sharapovavdg1972@list.ru',
                           'merkushevafxn1982@list.ru',
                           'shchukinaecs1970@list.ru',
                           'ztjxjmyzzvck@mynanaimohomes.com',
                           'kuznetsovabxq1972@list.ru',
                           '12ceeca360@emailfoxi.pro',
                           'blinovawvj1990@list.ru',
                           'golubevajli1995@list.ru',
                           'cimnujjo@mynanaimohomes.com',
                           'sazonovacxr1984@list.ru',
                           'vishnyakovafda1974@list.ru',
                           'rtyuinxwh@emlhub.com',
                           'f3d2122da4@emailfoxi.pro',
                           'naumovatas1989@list.ru',
                           'komarovavbf1987@list.ru',
                           'safonovaqoy1978@list.ru',
                           'samsonovagoe1980@list.ru',
                           'kozhenkolistar@mail.ru',
                           'dnrlge@muatoc.com',
                           'terentevabsj1994@list.ru',
                           'turovaksi1986@list.ru',
                           '61aedeb869@emailfoxi.pro',
                           'sitnikovacwo1976@list.ru',
                           'vasilevacav1979@list.ru',
                           'vladimirovajem1970@list.ru',
                           'dementevaxmn1992@list.ru',
                           'nrehvwlushwnk@mynanaimohomes.com',
                           'belyaevalgv1977@list.ru',
                           'borisovadmj1988@list.ru',
                           '49f62b5f28@emailfoxi.pro',
                           'golubevannn1969@list.ru',
                           'nosovadjp1986@list.ru',
                           '047d2memyw@spymail.one',
                           'isakovaayw1993@list.ru',
                           'avdeevakop1994@list.ru',
                           'kostinakbn1977@list.ru',
                           'hjiaguietxcfd@mynanaimohomes.com',
                           'popovakld1981@list.ru',
                           'e61dc84b69@emailfoxi.pro',
                           'fyodorovafoy1976@list.ru',
                           'drrthrnjidvur@miteon.com',
                           'evseevasnk1992@list.ru',
                           'morozovajkz1987@list.ru',
                           'mironovaang1968@list.ru',
                           'lazarevaqgf1983@list.ru',
                           'panovaybm1976@list.ru',
                           'vlasovadwi1979@list.ru',
                           'gushchinagbk1973@list.ru',
                           '9faceb9815@emailfoxi.pro',
                           '04fj89mjgg@freeml.net',
                           'kyjptnckk@miteon.com',
                           'zhuravlyovabrp1975@list.ru',
                           'y7dxfdj1@minimail.gq',
                           'kulikovafmr1981@list.ru',
                           '5121988b04@emailfoxi.pro',
                           'vlasovambj1987@list.ru',
                           'ceoxdrwtb@mynanaimohomes.com',
                           'zhukovaljf1997@list.ru',
                           'y7dxyx2m@minimail.gq',
                           'petrovausf1989@list.ru',
                           'avdeevaxja1982@list.ru',
                           'filatovaeou1976@list.ru',
                           'nblsavyoy@muatoc.com',
                           'orekhovaxvd1968@list.ru',
                           'y7dyjdh2@minimail.gq',
                           'd9a322c208@emailfoxi.pro',
                           'evdokimovapod1988@list.ru',
                           'korolyovabwc1987@list.ru',
                           'mukhinaqam1978@list.ru',
                           'vasilevaqlg1982@list.ru',
                           'nikolaevasxb1973@list.ru',
                           'mironovaczg1988@list.ru',
                           'dlmafn@mynanaimohomes.com',
                           'sharapovavnr1968@list.ru',
                           'agbbrlaoegvddd@dropmail.me',
                           'yudinaars1990@list.ru',
                           'bznnzpdxyde@muatoc.com',
                           '047d2yfr1c@spymail.one',
                           '40031adf99@emailfoxi.pro',
                           'smirnovauwy1988@list.ru',
                           'y6jr66fk@minimail.gq',
                           'grigorevaykm1971@list.ru',
                           'aqkomnemzj@miteon.com',
                           'tarasovaqcj1971@list.ru',
                           'ce6620391e@emailfoxi.pro',
                           'panovabsh1990@list.ru',
                           'belovarpm1997@list.ru',
                           'nqahxctfkh@mynanaimohomes.com',
                           'maslovanaa1975@list.ru',
                           'sharapovaiyg1977@list.ru',
                           'mwvabdxaj@emltmp.com',
                           'd7c1057a29@emailfoxi.pro',
                           'rybakovaslb1989@list.ru',
                           'danilovadex1989@list.ru',
                           'cfjwluyas@miteon.com',
                           'subbotinaxdq1978@list.ru',
                           'kryukovatrv1969@list.ru',
                           'burovamli1974@list.ru',
                           'tikhonovaquq1992@list.ru',
                           '047d34wt44@spymail.one',
                           'nosovaxak1969@list.ru',
                           'fadeevaqrm1985@list.ru',
                           'tvtuyx@mynanaimohomes.com',
                           '87ec2a8b6d@emailfoxi.pro',
                           'gssvujxzh@emlpro.com',
                           'lapinaufj1997@list.ru',
                           'andreevaiil1971@list.ru',
                           'panfilovaeiu1983@list.ru',
                           'aksyonovatof1974@list.ru',
                           'gusevaebk1980@list.ru',
                           'rogovafgd1974@list.ru',
                           'oaiypkc@miteon.com',
                           'jtrlhdxaj@emltmp.com',
                           'ovchinnikovaima1991@list.ru',
                           'mikhaylovauad1968@list.ru',
                           'lukinanfv1987@list.ru',
                           'uaurjsif@maxamba.com',
                           'emelyanovawya1995@list.ru',
                           'xs5n6sqj@flymail.tk',
                           'ermakovakkb1972@list.ru',
                           'titovaeat1997@list.ru',
                           'komarovawjp1987@list.ru',
                           'ahikmqjyb@10mail.org',
                           'krylovameu1983@list.ru',
                           '15e5bd6a9e@emailfoxi.pro',
                           'tsvetkovagzf1991@list.ru',
                           'zykovasim1966@list.ru',
                           'makarovalnf1984@list.ru',
                           'suwrbn@nespressopixie.com',
                           'm0vyb1b1zyv3@10mail.xyz',
                           'smirnovaugm1979@list.ru',
                           'vorobyovaspr1977@list.ru',
                           'ahihcuova@10mail.org',
                           'ryabovadbr1986@list.ru',
                           'nnaoxdtqmevgb@maxamba.com',
                           'fd6929884d@emailfoxi.pro',
                           'qloondxaj@emltmp.com',
                           'eliseevadkx1978@list.ru',
                           'icmqxvecrztqbxv@maxamba.com',
                           'ponomaryovatbc1983@list.ru',
                           'grishinabxs1996@list.ru',
                           'frolovafie1973@list.ru',
                           'gromovavrq1973@list.ru',
                           'belyakovacxl1982@list.ru',
                           '047d3rn7a8@spymail.one',
                           'gorbachyovalpj1977@list.ru',
                           'kovalyovaxbs1977@list.ru',
                           'zpkjehnxyvpogvd@miteon.com',
                           'a472c496a6@emailfoxi.pro',
                           'zyubcmojg@laste.ml',
                           'gavrilovaqft1973@list.ru',
                           'agbbsjxoswkobe@dropmail.me',
                           'loginovadbb1969@list.ru',
                           '7e3d81ddab@emailfoxi.pro',
                           'lebedevaaje1997@list.ru',
                           'gorbunovarhk1972@list.ru',
                           'y7e7tbze@minimail.gq',
                           'odintsovaktc1971@list.ru',
                           'belousovacpe1973@list.ru',
                           'gorbachyovadiq1991@list.ru',
                           'ahiknisxw@10mail.org',
                           'fokinambb1988@list.ru',
                           'gorbunovahyl1970@list.ru',
                           'kiselyovaycj1971@list.ru',
                           'cd65b8d2bf@emailfoxi.pro',
                           'zuevamhr1990@list.ru',
                           'khokhlovahkc1985@list.ru',
                           'odauhmojg@laste.ml',
                           'isakovafxd1972@list.ru',
                           'kopylovalom1990@list.ru',
                           'shchukinaxow1981@list.ru',
                           '890816a2d3@emailfoxi.pro',
                           'miphkmojg@laste.ml',
                           'lapinafjx1985@list.ru',
                           'terentevazms1978@list.ru',
                           'vorontsovaago1997@list.ru',
                           'khokhlovabdg1972@list.ru',
                           'tikhonovaqqe1973@list.ru',
                           '973reine@rustyload.com',
                           '24498b66a2@emailfoxi.pro',
                           'drozdovazym1997@list.ru',
                           'rlefvmdyzs@miteon.com',
                           'f44f3ff9f1@emailfoxi.pro',
                           'nhwbiljle@mynanaimohomes.com',
                           '7565d86167@emailfoxi.pro',
                           'jszrdutclnyaerb@mynanaimohomes.com',
                           'hrxtpkxiazuea@muatoc.com',
                           'nrpxwwzsd@maxamba.com',
                           'luuswqsazq@nespressopixie.com',
                           '620dd46cc3@emailfoxi.pro',
                           'smirnovapoi1995@list.ru',
                           'baalxnjh@nespressopixie.com',
                           'fac998ca6e@emailfoxi.pro',
                           'jgebstql@mynanaimohomes.com',
                           'akpqjvrguu@miteon.com',
                           'ixj9ahd1@maxamba.com',
                           '408b8e26da@emailfoxi.pro',
                           'ngvy82tr@maxamba.com',
                           'ulghwcwq@miteon.com',
                           'u735ztcd@maxamba.com',
                           'chernovawja1995@list.ru',
                           'gusevagaf1985@list.ru',
                           'mamontovatqk1990@list.ru',
                           'fjhwpeqzurv@miteon.com',
                           'popovalwi1982@list.ru',
                           'seliverstovazhg1971@list.ru',
                           'gushchinatnv1969@list.ru',
                           'ptrnnawf@maxamba.com',
                           'kolobovanqg1986@list.ru',
                           'veselovaghz1992@list.ru',
                           'ponomaryovaatc1977@list.ru',
                           'gordeevasix1970@list.ru',
                           'volkovavth1975@list.ru',
                           'vorobyovaxdf1989@list.ru',
                           'jftmwvnz@maxamba.com',
                           'ikitturoh@maxamba.com',
                           'ujvo5o1q@maxamba.com',
                           'antonovaucd1976@list.ru',
                           '86r122zx@maxamba.com',
                           'bxfjcfm@miteon.com',
                           'b1l8qdnj@maxamba.com',
                           '8jht79j0@maxamba.com',
                           'kknschc@muatoc.com',
                           'vorontsovacjp1997@list.ru',
                           'sim5r6zb@maxamba.com',
                           'komarovatby1987@list.ru',
                           'ignatovaumt1972@list.ru',
                           'bobrovatnu1992@list.ru',
                           'mjtaifmp@maxamba.com',
                           'vlbtvvdb@nespressopixie.com',
                           'dvvg6pic@maxamba.com',
                           'lebedevavrv1994@list.ru',
                           'mironovaryx1972@list.ru',
                           'avdeevaqxi1996@list.ru',
                           'voqhi2rl@maxamba.com',
                           'kabanovaoyu1994@list.ru',
                           'fcyzoe@muatoc.com',
                           'nikiforovauhl1966@list.ru',
                           'kotovacbw1985@list.ru',
                           'kw3pjza3@maxamba.com',
                           'sorokinahzw1987@list.ru',
                           '6mlsmsmv@maxamba.com',
                           'llexjjrmt@nespressopixie.com',
                           'antonovabig1994@list.ru',
                           'o5ws3ms6@maxamba.com',
                           'fedoseevanch1986@list.ru',
                           'sjxnwgieezixh@muatoc.com',
                           '0r1u1m04@maxamba.com',
                           'muravyovaarp1981@list.ru',
                           'simonovanzt1992@list.ru',
                           'qyue3s4n@maxamba.com',
                           'egorovaary1966@list.ru',
                           'krasilnikovadrk1978@list.ru',
                           'aahhvucjvjn@miteon.com',
                           '3fpltrdh@maxamba.com',
                           'makarovaqtt1966@list.ru',
                           '94njiibi@maxamba.com',
                           'lebedevauii1977@list.ru',
                           'lattznojg@laste.ml',
                           'tuiiqfsupetcrg@muatoc.com',
                           'xghqsrvn@maxamba.com',
                           'grishinaanx1988@list.ru',
                           'lapinaqgj1995@list.ru',
                           '292fbbsc@maxamba.com',
                           'xs6chvxh@flymail.tk',
                           'konovalovaoif1976@list.ru',
                           'wzisbgnwl@mynanaimohomes.com',
                           'veselovacen1992@list.ru',
                           '0kfc7sk1@maxamba.com',
                           'vasilevaugx1966@list.ru',
                           'fomichyovaoth1983@list.ru',
                           '04fjcf97sr@freeml.net',
                           'kovalyovadvq1995@list.ru',
                           'oxezvuj6@maxamba.com',
                           'xdezjqr@muatoc.com',
                           'danilovalar1991@list.ru',
                           'jlt3j4pq@maxamba.com',
                           'shubinamia1968@list.ru',
                           'fadeevagjj1986@list.ru',
                           'hkyn92gy@maxamba.com',
                           'sukhanovaect1971@list.ru',
                           'ozicdjltj@muatoc.com',
                           'yudinaget1984@list.ru',
                           'x0r28h2q@maxamba.com',
                           '0b00129561@emailfoxi.pro',
                           'nujavabunyk2@10mail.xyz',
                           'terentevamxg1984@list.ru',
                           '3dsy4qnd@maxamba.com',
                           'yylvbyaqg@nespressopixie.com',
                           'evdokimovatzc1987@list.ru',
                           'andreevawll1970@list.ru',
                           'lobanovaeti1966@list.ru',
                           'belyaevagoh1990@list.ru',
                           'n9uc8qoo@maxamba.com',
                           '8ea7ea911d@emailfoxi.pro',
                           'rhhlapdrub@mynanaimohomes.com',
                           'sk41qfrl@maxamba.com',
                           'agbbvmtrvdbmba@dropmail.me',
                           'zakharovaxcg1966@list.ru',
                           'ermakovabmh1986@list.ru',
                           '78ct64x2@maxamba.com',
                           'mamontovalrq1974@list.ru',
                           'qny36f8p@maxamba.com',
                           'xyupdcyub@nespressopixie.com',
                           '3a5a2e7d2b@emailfoxi.pro',
                           'zusgsqxwh@emlhub.com',
                           'yvmbwgg7@maxamba.com',
                           'gavrilovajya1991@list.ru',
                           'lebedevaeky1968@list.ru',
                           'smirnovatfx1977@list.ru',
                           'sidorovanoj1968@list.ru',
                           'om8vhtl1@maxamba.com',
                           'nxpupprge@nespressopixie.com',
                           'agbbvycaemyoaj@dropmail.me',
                           'orekhovaoru1966@list.ru',
                           '3c0fdb46cc@emailfoxi.pro',
                           'rybakovayad1966@list.ru',
                           'n3bhq67k@maxamba.com',
                           'ioy53znt@maxamba.com',
                           'ftctlfoxwx@nespressopixie.com',
                           'xs6myb7d@flymail.tk',
                           'lukinarbx1997@list.ru',
                           'mxpubh82@maxamba.com',
                           'b63a59699a@emailfoxi.pro',
                           'n7sfst45@maxamba.com',
                           'moiseevaadg1967@list.ru',
                           'g.ilb.er.t.o.a.r.c.hie.2@gmail.com',
                           'h.a.s.aba.h.mb.i.jo.mb.i@gmail.com',
                           'lytkinawqo1984@list.ru',
                           'abayedris+derrick@googlemail.com',
                           'cgy68140@nowni.com',
                           'mikheevasle1993@list.ru',
                           'egorovartk1976@list.ru',
                           'i.n.tr.epidn.mw@gmail.com',
                           'gusevauvo1983@list.ru',
                           'dn.d.n.g.z.msnf.smbt@gmail.com',
                           'romanovaxhh1993@list.ru',
                           'i.n.tre.p.i.d.nmw@gmail.com',
                           'wiwal1bud1m3@10mail.xyz',
                           'h.a.sa.b.a.h.m.b.i.jo.mb.i@gmail.com',
                           'zhdanovagla1978@list.ru',
                           'h.agaf.a.a.r.h.a.g.a.fa.re@gmail.com',
                           'burovatva1973@list.ru',
                           'tnbasadzoz@mynanaimohomes.com',
                           'hasanhgsagin+kenyon@googlemail.com',
                           'rybakovaqio1990@list.ru',
                           'agbbomkkmspdqv@dropmail.me',
                           'txupstf@nespressopixie.com',
                           'agbboyeaootbbd@dropmail.me',
                           'zthysirf@mynanaimohomes.com',
                           'b2b39c60d2@emailfoxi.pro',
                           'agbbfbzrmodajo-8u@xhgk.dropmail.me',
                           'xxwprzift@maxamba.com',
                           'zuevatvn1991@list.ru',
                           '02debc3cd7@emailfoxi.pro',
                           'muvokol1gyw3@10mail.xyz',
                           'bgk72807@dcobe.com',
                           'nqwtkzzfwlqv@muatoc.com',
                           'zuevaecz1994@list.ru',
                           'ahikytuah@10mail.org',
                           '3a0fe9151e@emailfoxi.pro',
                           'unqeggaut@muatoc.com',
                           'wfedwkxaj@emltmp.com',
                           'fskevvxwh@emlhub.com',
                           'txzykkujxiy@muatoc.com',
                           'filatovaams1979@list.ru',
                           'agbbdjbvltwonb@dropmail.me',
                           'iuiqioqt@nespressopixie.com',
                           'abramovajth1971@list.ru',
                           'agbbdoopdfceva@dropmail.me',
                           'awqeostpijsgotz@maxamba.com',
                           'ffc5548c8d@emailfoxi.pro',
                           'qzevgvxmdiqz@maxamba.com',
                           '04fjmt3g38@freeml.net',
                           'e7c28488ed@emailfoxi.pro',
                           'zzmnfml@miteon.com',
                           'cpxunuojg@laste.ml',
                           '509fee7486@emailfoxi.pro',
                           'jhtzupbghpu@nespressopixie.com',
                           'slxjnsxzh@emlpro.com',
                           'rup77058@nowni.com',
                           'fokinapuf1986@list.ru',
                           '22381b012b@emailfoxi.pro',
                           'txrewwgj@mynanaimohomes.com',
                           '047dftewkw@spymail.one',
                           'otkghvncdg@mynanaimohomes.com',
                           'tljhuwxwh@emlhub.com',
                           '59ac8c5605@emailfoxi.pro',
                           'agbbezhicuubne@dropmail.me',
                           '38ff2ea821@emailfoxi.pro',
                           'romanovadqn1971@list.ru',
                           'seleznyovaqtr1985@list.ru',
                           'sidorovamhv1973@list.ru',
                           'lavrentevanjf1977@list.ru',
                           'tikhonovahyh1971@list.ru',
                           'fedoseevafzf1987@list.ru',
                           'sukdtxxzh@emlpro.com',
                           'nazarovamzz1972@list.ru',
                           'kolesnikovaojx1989@list.ru',
                           'timofeevagai1993@list.ru',
                           'doroninawwu1979@list.ru',
                           'kalashnikovaenk1976@list.ru',
                           'likhachyovaluv1995@list.ru',
                           'qzjzacywh@emlhub.com',
                           'gavrilovaxcv1977@list.ru',
                           'subbotinacvw1993@list.ru',
                           'osipovawag1983@list.ru',
                           'antonovabxt1976@list.ru',
                           'khokhlovazwj1981@list.ru',
                           'nikonovakjm1989@list.ru',
                           'xsaqw4tx@flymail.tk',
                           'oiysdikpqaej@maxamba.com',
                           'shiryaevazyw1989@list.ru',
                           'y7k89rh9@minimail.gq',
                           'sitnikovadlf1968@list.ru',
                           'kkvevhwwfl@muatoc.com',
                           'terentevaupt1991@list.ru',
                           'samsonovaaal1966@list.ru',
                           'moiseevavts1977@list.ru',
                           'kononovaomg1995@list.ru',
                           'ahildnjgo@10mail.org',
                           'nsvzbiwsqd@muatoc.com',
                           'mishinahbd1990@list.ru',
                           'petukhovahtd1986@list.ru',
                           'kiselyovafgv1970@list.ru',
                           'zinovevansy1975@list.ru',
                           'nazarovausa1993@list.ru',
                           '047drgqcx4@spymail.one',
                           'terentevaahc1983@list.ru',
                           'b90f0508d0@emailfoxi.pro',
                           'nqtutqwuzna@nespressopixie.com',
                           'trofimovadcr1993@list.ru',
                           'ignatovatwu1976@list.ru',
                           'wjvxxyxzh@emlpro.com',
                           'ignatevaspu1971@list.ru',
                           'mamontovapzz1982@list.ru',
                           'solovyovakea1996@list.ru',
                           'qrhycyzkh@nespressopixie.com',
                           'ahilelxav@10mail.org',
                           'drozdovagyy1973@list.ru',
                           'savelevaknw1970@list.ru',
                           'mghpnllt@mynanaimohomes.com',
                           'kostinamux1970@list.ru',
                           'gttjmdywh@emlhub.com',
                           '49c600272c@emailfoxi.pro',
                           'luzsjpmsaqcan@mynanaimohomes.com',
                           'scahrsxaj@emltmp.com',
                           'ignatovapia1973@list.ru',
                           'vinogradovalkq1983@list.ru',
                           'b275902afc@emailfoxi.pro',
                           'dxpjafrovntmv@miteon.com',
                           'filippovarht1975@list.ru',
                           'efimovahjv1992@list.ru',
                           'mikhaylovaaof1988@list.ru',
                           'morozovajdz1978@list.ru',
                           'y7kt2bs1@minimail.gq',
                           'emelyanovamqi1984@list.ru',
                           'kostinakuc1986@list.ru',
                           'karpovatpx1973@list.ru',
                           'nulfhrfn@miteon.com',
                           'uzg46727@dcobe.com',
                           '5ea906848a@emailfoxi.pro',
                           'blokhinapvc1977@list.ru',
                           'qehojaxekubr@nespressopixie.com',
                           'morozovaykm1976@list.ru',
                           '3f5da9b224@emailfoxi.pro',
                           'bykovaexo1981@list.ru',
                           'gavrilovanty1985@list.ru',
                           'pakhomovacpp1980@list.ru',
                           'vorobyovancr1981@list.ru',
                           'bobrovacem1966@list.ru',
                           'gavrilovacrd1970@list.ru',
                           'mikheevaqis1979@list.ru',
                           'sharapovanqa1993@list.ru',
                           'kaslojorgod@mynanaimohomes.com',
                           'nosovatck1979@list.ru',
                           'popovakvg1976@list.ru',
                           'nikonovauyu1977@list.ru',
                           'kornilovaczh1975@list.ru',
                           'shubinabsb1988@list.ru',
                           'utdyygq@maxamba.com',
                           'mishinadeo1984@list.ru',
                           'yakovlevagea1977@list.ru',
                           'safonovarqi1977@list.ru',
                           'xqoejklezxalg@mynanaimohomes.com',
                           'petukhovasyq1966@list.ru',
                           'gushchinaacd1978@list.ru',
                           'simonovamms1970@list.ru',
                           'voronovaejs1985@list.ru',
                           'silinagwu1969@list.ru',
                           'dae0f7ece8@emailfoxi.pro',
                           'samoylovanzc1991@list.ru',
                           'bespalovawkx1984@list.ru',
                           'kopylovarhz1973@list.ru',
                           'sokolovabqe1982@list.ru',
                           'rwn10553@nowni.com',
                           'f48e837921@emailfoxi.pro',
                           'lavrentevabkt1973@list.ru',
                           'artemevabjw1981@list.ru',
                           'lazarevatrg1977@list.ru',
                           'bobylyovauzd1984@list.ru',
                           'lebedevajtq1970@list.ru',
                           'terentevasvw1972@list.ru',
                           'terentevayrg1987@list.ru',
                           'bogdanovawqr1989@list.ru',
                           'sorokinaqcg1992@list.ru',
                           'fyodorovanwk1969@list.ru',
                           'myasnikovaatt1989@list.ru',
                           'zaytsevavvi1970@list.ru',
                           'krasilnikovajgi1966@list.ru',
                           'shcherbakovaotm1970@list.ru',
                           'sukhanovabap1968@list.ru',
                           'shiryaevakdr1972@list.ru',
                           'maksimovabtz1983@list.ru',
                           'krasilnikovabds1973@list.ru',
                           'sergeevamds1986@list.ru',
                           'knyazevaqfw1990@list.ru',
                           'evseevazrw1984@list.ru',
                           'aksyonovasbo1966@list.ru',
                           '87ccf8443c@emailfoxi.pro',
                           'konovalovacet1966@list.ru',
                           'belyakovawjv1979@list.ru',
                           'kostinauhj1968@list.ru',
                           'kharitonovayyp1967@list.ru',
                           'panovarty1973@list.ru',
                           'c8c75cda50@emailfoxi.pro',
                           'galkinazaf1982@list.ru',
                           'belousovacod1969@list.ru',
                           'burovakyy1979@list.ru',
                           'molchanovamec1991@list.ru',
                           'ignatevasgd1986@list.ru',
                           'aa95852422@emailfoxi.pro',
                           'naumovandg1992@list.ru',
                           'larionovalgl1976@list.ru',
                           'suvorovawtg1988@list.ru',
                           'kotovabfe1975@list.ru',
                           'timofeevagae1985@list.ru',
                           'mukhinawsk1967@list.ru',
                           'sharapovapnc1983@list.ru',
                           '2f39ce88dd@emailfoxi.pro',
                           'evseevanfa1987@list.ru',
                           'kulakovaagu1977@list.ru',
                           'petrovamys1985@list.ru',
                           '7722925c82@emailfoxi.pro',
                           'rusakovaelz1987@list.ru',
                           'vishnyakovajje1968@list.ru',
                           'orekhovatbx1986@list.ru',
                           'bykovakso1969@list.ru',
                           'd60bb91af1@emailfoxi.pro',
                           'petrovaxnz1967@list.ru',
                           'silinamgz1985@list.ru',
                           'teterinawxz1988@list.ru',
                           'd8d71a434c@emailfoxi.pro',
                           'vladimirovayrz1968@list.ru',
                           'kononovaaxl1983@list.ru',
                           'kiselyovauuq1995@list.ru',
                           'mukhinazqm1973@list.ru',
                           'belozyorovatih1977@list.ru',
                           'koshelevaeiw1995@list.ru',
                           'b8eff137a2@emailfoxi.pro',
                           '1f05a85c52@emailfoxi.pro',
                           'yudinavfy1990@list.ru',
                           'lavrentevabao1978@list.ru',
                           'belyaevaiba1988@list.ru',
                           'sharapovatat1967@list.ru',
                           'shiryaevatmt1997@list.ru',
                           'konovalovaejr1984@list.ru',
                           '6a513d89a0@emailfoxi.pro',
                           '4cd0cb6dff@emailfoxi.pro',
                           'kolobovabeh1987@list.ru',
                           'aleksandrovampq1988@list.ru',
                           'kuznetsovaruh1983@list.ru',
                           'vlasovahxy1996@list.ru',
                           'alekseevauqq1997@list.ru',
                           'd8a38b9b20@emailfoxi.pro',
                           'ad7aa2eeff@emailfoxi.pro',
                           'makarovaysx1977@list.ru',
                           'prokhorovafsi1975@list.ru',
                           'emelyanovadcl1992@list.ru',
                           '147bd1adff@emailfoxi.pro',
                           'gordeevaoik1985@list.ru',
                           'ilinamfa1971@list.ru',
                           'silinatmi1971@list.ru',
                           'yakushevautz1995@list.ru',
                           'grishinazkd1994@list.ru',
                           'myasnikovauus1987@list.ru',
                           'braginabex1977@list.ru',
                           'yakovlevakkf1966@list.ru',
                           'braginazih1997@list.ru',
                           'maksimovagwx1975@list.ru',
                           'avdeevauza1977@list.ru',
                           'gusevabgi1968@list.ru',
                           'stepanovainp1974@list.ru',
                           'bespalovatas1968@list.ru',
                           'panovahms1972@list.ru',
                           '9af9442d0b@emailfoxi.pro',
                           '0fa61022ab@emailfoxi.pro',
                           'panovagwh1977@list.ru',
                           'molchanovapvy1971@list.ru',
                           'mishinagoo1966@list.ru',
                           'anisimovaldx1973@list.ru',
                           '7fcd4d9763@emailfoxi.pro',
                           'voronovasew1975@list.ru',
                           '1cb54cc0cb@emailfoxi.pro',
                           'terentevaufq1969@list.ru',
                           'grishinalkm1974@list.ru',
                           'romanovaavk1997@list.ru',
                           'bykovapwb1977@list.ru',
                           'panfilovakiq1986@list.ru',
                           'efremovafdh1972@list.ru',
                           'a50eda7f87@emailfoxi.pro',
                           'kornilovagnq1974@list.ru',
                           '4ff9b051bb@emailfoxi.pro',
                           'c8ce656fc7@emailfoxi.pro',
                           'gulyaevadsc1968@list.ru',
                           'kuzminacay1969@list.ru',
                           'bolshakovahlx1968@list.ru',
                           'denisovaxel1980@list.ru',
                           '17b48058a9@emailfoxi.pro',
                           'khokhlovafyj1993@list.ru',
                           'a36819e4c4@emailfoxi.pro',
                           'matveevagyv1993@list.ru',
                           'evdokimovaxkf1972@list.ru',
                           '089106ab33@emailfoxi.pro',
                           'artemevajuw1985@list.ru',
                           'safonovafnk1997@list.ru',
                           'gordeevahql1967@list.ru',
                           'gorshkovazgx1978@list.ru',
                           'agafonovauiu1985@list.ru',
                           'avdeevawry1975@list.ru',
                           '5fed9e1930@emailfoxi.pro',
                           '12d6fb2fba@emailfoxi.pro',
                           'kiselyovarre1972@list.ru',
                           'ahabgbzafbyrse@dropmail.me',
                           'fyodorovagfo1979@list.ru',
                           'kuznetsovajrh1978@list.ru',
                           'suvorovanyz1975@list.ru',
                           'prokhorovaowj1996@list.ru',
                           'patebygehup3@10mail.xyz',
                           'xskn1bc7@flymail.tk',
                           'ermakovahea1990@list.ru',
                           'dd382ecc5e@emailfoxi.pro',
                           'cf7b568c1c@emailfoxi.pro',
                           '0c2149c5e1@emailfoxi.pro',
                           '047g1wf498@spymail.one',
                           'zz745214@maxamba.com',
                           'rplorprroor@gmail.com',
                           'vnq56780@dcobe.com'
            )

    `
    return {}
  }

  async createFile(
    path: string,
    fileName: string,
    data: string,
  ): Promise<void> {
    // if (!this.checkIfFileOrDirectoryExists(path)) {
    //   fs.mkdirSync(path);
    // }

    const writeFiles = promisify(writeFile);

    return await writeFiles(`${path}/${fileName}`, data, 'utf8');
  }

  async findManyUsersByName(name: string): Promise<any> {
    return this.dbService.user.findMany({
      take: 10,
      orderBy: {
        videoLikes: {
          _count: 'desc'
        }
      },
      where: {
        name: {
          contains: name
        }
      },
      include: {
        videoLikes: {
          select: {
            id: true,
            video_id: true,
            user: {
              select: {
                id: true,
              },
            },
          },
        }
      }
    })
  }

  async findFirstSongById(id: number): Promise<any> {
    const song = "https://firebasestorage.googleapis.com/v0/b/testing-98cd8.appspot.com/o/images%2F1725226282184?alt=media&token=5c0ccc8f-f8d1-4c65-8385-e21b695de6cb"
    const readStream = createReadStream(song)
    return new StreamableFile(readStream)
    return this.dbService.song.findFirst({
      where: {
        id: id
      }
    })
  }

}
